// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manam.GhepGan.DAL
{
    public partial class AccessToken
    {
        public long Id { get; set; }
        public Guid? AccountId { get; set; }
        public string AccessToken1 { get; set; }
        public string RefreshToken { get; set; }
        public int? ExpiresIn { get; set; }
    }
}