// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manam.GhepGan.DAL
{
    public partial class Comment
    {
        public long Id { get; set; }
        public long EntityId { get; set; }
        public string EntityType { get; set; }
        public long? ReplyToId { get; set; }
        public string Content { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Email { get; set; }
    }
}