// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Manam.GhepGan.DAL.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace Manam.GhepGan.DAL
{
    public partial class GhepGanDbContext : DbContext
    {
        public GhepGanDbContext()
        {
        }

        public GhepGanDbContext(DbContextOptions<GhepGanDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<News> News { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.AccountConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CommentConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.NewsConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
