// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manam.GhepGan.DAL
{
    public partial class News
    {
        public long Id { get; set; }
        public string Avatar { get; set; }
        public string UrlAlias { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public long ViewCount { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] VersionNo { get; set; }
    }
}