// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Manam.GhepGan.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Manam.GhepGan.DAL.Configurations
{
    public partial class AccessTokenConfiguration : IEntityTypeConfiguration<AccessToken>
    {
        public void Configure(EntityTypeBuilder<AccessToken> entity)
        {
            entity.ToTable("access_token");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.AccessToken1)
                .IsUnicode(false)
                .HasColumnName("access_token");

            entity.Property(e => e.AccountId).HasColumnName("account_id");

            entity.Property(e => e.ExpiresIn).HasColumnName("expires_in");

            entity.Property(e => e.RefreshToken)
                .IsUnicode(false)
                .HasColumnName("refresh_token");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccessToken> entity);
    }
}
