// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Manam.GhepGan.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Manam.GhepGan.DAL.Configurations
{
    public partial class AccountConfiguration : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> entity)
        {
            entity.ToTable("account");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedBy).HasColumnName("created_by");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");

            entity.Property(e => e.IsActive).HasColumnName("is_active");

            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");

            entity.Property(e => e.LastIpLogin)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("last_ip_login");

            entity.Property(e => e.LastLoginDate)
                .HasColumnType("datetime")
                .HasColumnName("last_login_date");

            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasColumnName("modified_date");

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("password");

            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasColumnName("username");

            entity.Property(e => e.VersionNo)
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("version_no");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Account> entity);
    }
}
