// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Manam.GhepGan.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Manam.GhepGan.DAL.Configurations
{
    public partial class CommentConfiguration : IEntityTypeConfiguration<Comment>
    {
        public void Configure(EntityTypeBuilder<Comment> entity)
        {
            entity.ToTable("comment");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasColumnName("created_by");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");

            entity.Property(e => e.EntityId).HasColumnName("entity_id");

            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("entity_type");

            entity.Property(e => e.ReplyToId).HasColumnName("reply_to_id");

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Comment> entity);
    }
}
