// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Manam.GhepGan.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Manam.GhepGan.DAL.Configurations
{
    public partial class NewsConfiguration : IEntityTypeConfiguration<News>
    {
        public void Configure(EntityTypeBuilder<News> entity)
        {
            entity.ToTable("news");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Avatar)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("avatar");

            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");

            entity.Property(e => e.CreatedBy).HasColumnName("created_by");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");

            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");

            entity.Property(e => e.ModifiedBy).HasColumnName("modified_by");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasColumnName("modified_date");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");

            entity.Property(e => e.UrlAlias)
                .IsRequired()
                .HasMaxLength(512)
                .IsUnicode(false)
                .HasColumnName("url_alias");

            entity.Property(e => e.VersionNo)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasColumnName("version_no");

            entity.Property(e => e.ViewCount).HasColumnName("view_count");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<News> entity);
    }
}
